name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          config_timezone: America/Santiago
          filename: metrics.classic.svg
          base: header, repositories
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          config_order: base.header, base.repositories, isocalendar, languages, lines, activity
          
